# Generated by Django 3.1.4 on 2021-01-05 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, message='This field cannot be blank')])),
                ('destination', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, message='This field cannot be blank')])),
                ('departure_date', models.CharField(max_length=100)),
                ('return_date', models.CharField(max_length=100)),
                ('oneway', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritelist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
