# Generated by Django 3.1.4 on 2021-01-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20210105_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelist',
            name='price',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
