# Generated by Django 3.1.4 on 2021-01-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_remove_favoritelist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
