# Generated by Django 3.1.4 on 2021-01-15 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_favoritelist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='destination',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='This field cannot be blank')]),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='origin',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='This field cannot be blank')]),
        ),
    ]
