# Generated by Django 3.1.4 on 2021-01-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_auto_20210115_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
